<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>AccessReelApp</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>AccessReelApp</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.accessreelapp</ApplicationId>
		<ApplicationIdGuid>222c4483-a7d8-452c-9fef-d90b9d96dca7</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />

	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\private_key.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="6.1.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="FirebaseAdmin" Version="2.4.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
		<PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.0-rc.2.23479.10" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3">
		  <TreatAsUsed>true</TreatAsUsed>
		</PackageReference>
		<PackageReference Include="Plugin.LocalNotification" Version="10.1.8" />
		<PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Views\InterviewsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\NewsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ReviewsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SignUpLogin.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
	  <PackageReference Include="Xamarin.AndroidX.AppCompat.AppCompatResources">
	    <Version>1.5.1</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Collection">
	    <Version>1.3.0.1</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Collection.Jvm">
	    <Version>1.3.0.1</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common">
	    <Version>2.6.2.2</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime">
	    <Version>2.6.2.2</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.Firebase.Messaging">
	    <Version>123.2.1.1</Version>
	    <TreatAsUsed>true</TreatAsUsed>
	  </PackageReference>
	  <PackageReference Include="Xamarin.GooglePlayServices.Base">
	    <Version>118.2.0.4</Version>
	    <TreatAsUsed>true</TreatAsUsed>
	  </PackageReference>
	  <PackageReference Include="Xamarin.GooglePlayServices.CloudMessaging">
	    <Version>117.0.2.7</Version>
	    <TreatAsUsed>true</TreatAsUsed>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-ios'">
	  <PackageReference Include="CommunityToolkit.Maui">
	    <Version>5.3.0</Version>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-maccatalyst'">
	  <PackageReference Include="CommunityToolkit.Maui">
	    <Version>5.3.0</Version>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-windows10.0.19041.0'">
	  <PackageReference Include="CommunityToolkit.Maui">
	    <Version>5.3.0</Version>
	  </PackageReference>
	</ItemGroup>

</Project>
